---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/hg3ads37/produto.huntersmotos.com.br/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -f index.html robots.txt sitemap.xml llm.txt llms.txt googlea7325cf7451ffaf9.html .htaccess "$DEPLOYPATH"
    - /bin/cp -R assets "$DEPLOYPATH"
